033[7;40mdigite algo')
print('o tipo primitivo desse valor é', type('a'))
print('só tem espaços', a.isspace())
print('só tem numeros', a.isnumeric())
print('só tem letas', a.isalpha())
print('é alfanumerico', a.isalnum())
print('só tem maiuscula', a.isupper())
print('só tem minuscula', a.islower())
print('é capitalizada', a.isprintable())
